### ISSUE TITLE
Dependency testing-util-lib causes conflict

### ISSUE THREAD

**Issue by khinsen** [jeapostrophe/chk#1]
With Racket 6.5, installation fails because of a conflict between testing-util-lib and rackunit. It looks like this is due to a recent reorganization of rackunit. I replaced testing-util-lib by rackunit in info.rkt, and everything works fine for me, but I am far from certain that this is the right fix, so I don't propose a pull request.

**Comment by wilbowma** [comment]
Just had a similar issue. See also: https://github.com/racket/rackunit/issues/24. My workaround is to require a more recent version of rackunit-lib as a build-dep.

**Comment by jeapostrophe** [comment]
I believe that the change to `rackunit` fixes these because `chk` has always required `testing-util-lib`

**Comment by wilbowma** [comment]
That workaround doesn't work when rackunit-lib is installed in installation scope, and the user can't update it. This may just be a limitation in Racket's package management.

**Comment by jeapostrophe** [comment]
I agree and thanks for the FYI on it.
