### ISSUE TITLE
Tests failing in package build server

### ISSUE THREAD

**Issue by jackfirth** [jeapostrophe/chk#3]
See [the transcript](http://pkg-build.racket-lang.org/server/built/test-fail/chk.txt). It's hard to tell if this is a real failure or if uses of `chk` that are meant to fail are logging failures with `test-log!` and being counted by `raco test`. If it's the latter, `test-log-enabled?` can be used to disable failure logging for these expressions.

**Comment by jeapostrophe** [comment]
Thanks, fixed!
