### ISSUE TITLE
chk with test-case doubles test count

### ISSUE THREAD

**Issue by camoy** [jeapostrophe/chk#6]
When you use `chk` with `test-case`:
```
#lang racket/base

(module+ test
  (require rackunit chk)
  (test-case "example"
    (chk 1 1)))
```

Running `raco test` will report two successes.
```
raco test: (submod "chk.rkt" test)
2 tests passed
```

**Comment by jeapostrophe** [comment]
`chk` is not intended to be used with `rackunit` (and therefore, `test-case`) as they are totally orthogonal testing libraries that each use the common test counting infrastructure. You may like [`rackunit-chk`](https://github.com/jeapostrophe/rackunit-chk), which is the precursor to `chk` that was supposed to work with `rackunit`.
